In [198]:
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import seaborn as sns
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import train_test_split
from surprise import KNNBasic
from surprise import accuracy
from surprise.model_selection import GridSearchCV
from joblib import dump, load
from sqlalchemy import create_engine
%reload_ext sql
%sql postgresql://studentrs:szcWuiyxVnKO38XfzHkP@workshop1rs.cevhjouwoh1r.us-east-2.rds.amazonaws.com/workshop_1


In [2]:
user_interact = pd.read_csv('data/lastfm-dataset-1K/userid-timestamp-artid-artname-traid-traname.tsv',
                  sep = '\t',
                 names = ['UserId', 'TimeStamp', 'ArtId', 'ArtName', 'TraId', 'TraName'])
user_interact.head()

UserId             TimeStamp                                 ArtId  \
0  user_000001  2009-05-04T23:08:57Z  f1b1cf71-bd35-4e99-8624-24a6e15f133a   
1  user_000001  2009-05-04T13:54:10Z  a7f7df4a-77d8-4f12-8acd-5c60c93f4de8   
2  user_000001  2009-05-04T13:52:04Z  a7f7df4a-77d8-4f12-8acd-5c60c93f4de8   
3  user_000001  2009-05-04T13:42:52Z  a7f7df4a-77d8-4f12-8acd-5c60c93f4de8   
4  user_000001  2009-05-04T13:42:11Z  a7f7df4a-77d8-4f12-8acd-5c60c93f4de8   

     ArtName TraId                                     TraName  
0  Deep Dish   NaN  Fuck Me Im Famous (Pacha Ibiza)-09-28-2007  
1       坂本龍一   NaN           Composition 0919 (Live_2009_4_15)  
2       坂本龍一   NaN                        Mc2 (Live_2009_4_15)  
3       坂本龍一   NaN                     Hibari (Live_2009_4_15)  
4       坂本龍一   NaN                        Mc1 (Live_2009_4_15)

In [3]:
aux_artistas = user_interact.groupby('UserId').agg({'ArtId':'nunique'}).reset_index().rename(columns = {'ArtId':'Nart'})
ratings_artistas = user_interact.groupby(['UserId', 'ArtId']).size().reset_index(name = 'frecuencia')
ratings_artistas['log_frecuencia'] = np.log10(ratings_artistas['frecuencia'])
ratings_artistas_merged = ratings_artistas.merge(aux_artistas, on = 'UserId', how = 'left')
ratings_artistas_merged['normalizada'] = ratings_artistas_merged['frecuencia']/ratings_artistas_merged['Nart']
ratings_artistas_merged = ratings_artistas_merged.drop('Nart', axis = 1)
temp_1 = ratings_artistas_merged.groupby('ArtId').size().reset_index(name = 'Frecuencia').sort_values('Frecuencia', ascending = False)
items_disponibles = list(temp_1['ArtId'][temp_1['Frecuencia'] > np.percentile(temp_1['Frecuencia'] , 90)].unique())
ratings_artistas_merged_item = ratings_artistas_merged[ratings_artistas_merged['ArtId'].isin(items_disponibles)]

In [196]:
np.log(algo.sim)

<ipython-input-196-92f7200b7f74>:1: RuntimeWarning: divide by zero encountered in log
  np.log(algo.sim)


array([[ 0.00000000e+00, -2.49352956e-01, -9.84406396e-01, ...,
        -1.69484623e+00,  0.00000000e+00, -1.30939572e+00],
       [-2.49352956e-01,  0.00000000e+00, -1.62247752e-01, ...,
                   -inf,            -inf,            -inf],
       [-9.84406396e-01, -1.62247752e-01,  0.00000000e+00, ...,
        -2.44353633e+00, -1.11246221e+00, -1.17247539e-01],
       ...,
       [-1.69484623e+00,            -inf, -2.44353633e+00, ...,
         0.00000000e+00,            -inf, -2.22044605e-16],
       [ 0.00000000e+00,            -inf, -1.11246221e+00, ...,
                   -inf,  0.00000000e+00,            -inf],
       [-1.30939572e+00,            -inf, -1.17247539e-01, ...,
        -2.22044605e-16,            -inf,  0.00000000e+00]])

In [197]:
algo.sim

array([[1.        , 0.77930486, 0.37366097, ..., 0.18362746, 1.        ,
        0.26998315],
       [0.77930486, 1.        , 0.85023053, ..., 0.        , 0.        ,
        0.        ],
       [0.37366097, 0.85023053, 1.        , ..., 0.08685317, 0.32874852,
        0.88936501],
       ...,
       [0.18362746, 0.        , 0.08685317, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.32874852, ..., 0.        , 1.        ,
        0.        ],
       [0.26998315, 0.        , 0.88936501, ..., 1.        , 0.        ,
        1.        ]])

In [193]:
items_disponibles = list(temp_1['ArtId'][temp_1['Frecuencia'] > np.percentile(temp_1['Frecuencia'] , 90)].unique())


In [194]:
len(items_disponibles)

10238

In [ ]:
temp = user_interact.groupby('ArtId').size().reset_index(name = 'Frecuencia').sort_values('Frecuencia', ascending = False)


In [6]:
reader = Reader(rating_scale = (min(ratings_artistas_merged_item['normalizada']),
                                        max(ratings_artistas_merged_item['normalizada']) ))

surprise_dataset = Dataset.load_from_df(ratings_artistas_merged_item[['UserId','ArtId','normalizada']],
                                                reader)

rating_data = surprise_dataset.build_full_trainset()


In [7]:
sim_options = {'name': 'cosine',
                       'user_based': False} 

algo = KNNBasic(k = 20, min_k = 2, sim_options = sim_options)
algo.fit(rating_data)

Computing the cosine similarity matrix...
Done computing similarity matrix.


In [166]:
algo.sim

array([[1.        , 0.77930486, 0.37366097, ..., 0.18362746, 1.        ,
        0.26998315],
       [0.77930486, 1.        , 0.85023053, ..., 0.        , 0.        ,
        0.        ],
       [0.37366097, 0.85023053, 1.        , ..., 0.08685317, 0.32874852,
        0.88936501],
       ...,
       [0.18362746, 0.        , 0.08685317, ..., 1.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.32874852, ..., 0.        , 1.        ,
        0.        ],
       [0.26998315, 0.        , 0.88936501, ..., 1.        , 0.        ,
        1.        ]])

In [163]:
%%time
items = []
nearest = []
df_test = pd.DataFrame()
for iid in rating_data.ir.keys():
    temp = pd.DataFrame()
    temp = temp.assign(c_iid = [rating_data.to_raw_iid(i) for i in algo.get_neighbors(iid, 10)])
    temp = temp.assign(item_iid = rating_data.to_raw_iid(iid))
    temp = temp.assign(rating = algo.sim[iid][algo.get_neighbors(iid, 10)])
    df_test = pd.concat([df_test,temp], axis = 0)
    


Wall time: 4min 6s


In [182]:
df_test_final = df_test.reset_index().rename(columns = {'index':'id', 'item_iid':'base_artist', 'c_iid':'artist_id'})[['id','base_artist','rating','artist_id']]
df_test_final

id                           base_artist  rating  \
0            0  0356daee-ec48-4495-bc3e-460b8a5eacad     1.0   
1            1  0356daee-ec48-4495-bc3e-460b8a5eacad     1.0   
2            2  0356daee-ec48-4495-bc3e-460b8a5eacad     1.0   
3            3  0356daee-ec48-4495-bc3e-460b8a5eacad     1.0   
4            4  0356daee-ec48-4495-bc3e-460b8a5eacad     1.0   
...        ...                                   ...     ...   
102375  102375  089f526f-1ddf-4aef-85d7-fed8d234e59b     1.0   
102376  102376  089f526f-1ddf-4aef-85d7-fed8d234e59b     1.0   
102377  102377  089f526f-1ddf-4aef-85d7-fed8d234e59b     1.0   
102378  102378  089f526f-1ddf-4aef-85d7-fed8d234e59b     1.0   
102379  102379  089f526f-1ddf-4aef-85d7-fed8d234e59b     1.0   

                                   artist_id  
0       2a2259df-72c3-4d22-96de-8744a0dd6d6b  
1       97ce95e8-7f34-487e-9b4c-6c02f70bf9fb  
2       9d123f67-4998-42ad-9e6c-35ad7dc97aa8  
3       aee61f0d-d42e-4dcd-94b7-6a3f81e4c0d6  
4       e9a4a145-e1bd-4384-ad26-b344205dd9df  
...                                      ...  
102375  c62e843e-cb0c-4f11-b2e5-cd7cb7ad81bc  
102376  c6d2cbdf-30e7-4233-a1b4-e892f116ada1  
102377  302ae60e-4c6f-444b-9a1f-8aa5f3aed57e  
102378  34cf95c7-4be9-4efd-a48a-c2ea4a0bb114  
102379  0dcf7f6e-da64-4fa7-bc80-5950c55fa8d2  

[102380 rows x 4 columns]

In [186]:
df_test_final.to_csv('similarities.csv', index = False)

In [199]:
%%time
%sql \copy items_similarity (id, base_artist, rating, artist_id) FROM 'similarities.csv' with(format CSV, header, delimiter ',', quote '\"', escape '''');

 * postgresql://studentrs:***@workshop1rs.cevhjouwoh1r.us-east-2.rds.amazonaws.com/workshop_1
0 rows affected.
Wall time: 4.5 s


[]